config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, except: :show do
    member do
      get 'donation_pending_amounts'
    end
  end
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"

  resource :donations, only: [:new] #, :create]
  root 'home#index'
  # root 'welcome#index'
  resources :reports, only: [] do 
    collection do 
      get :collections
      get :submissions
      get :pendings
      get :coordinator_submissions
    end
  end

  resources :donation_submissions, only: [:new, :create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.haml
<a href="http://www.joshsoftware.com" target="_blank"> Developed by Josh Software </a> 

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{'aria-controls' => 'navbar', 'aria-expanded' => 'false', 'data-target' => '#navbar', 'data-toggle' => 'collapse', :type => 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => '/'} Seva Sahayog Donations 
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if current_user.is_admin?
          %li
            = link_to "Make Donation Collection Entries", new_donation_submission_path
        %li
          = link_to "Make New Donation", new_donations_path
        %li.dropdown
          %a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"} 
            Reports
            %b.caret
            %ul.dropdown-menu{"role" => "menu"}
              - if current_user.is_admin?
                %li= link_to 'Manage Users', users_path
                %li= link_to 'Collection', collections_reports_path
                %li= link_to 'Submission', submissions_reports_path
                %li= link_to 'Pending', pendings_reports_path
              - else
                %li= link_to 'Collection', collections_reports_path
                %li= link_to 'Submission', coordinator_submissions_reports_path
        %li.dropdown
          %a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"}
            = current_user.display_name
            %b.caret
            %ul.dropdown-menu{"role" => "menu"}
              /%li= link_to "Change Password", edit_user_registration_path(current_user)
              %li= link_to "Sign out", destroy_user_session_path, :method => :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: 'viewport', content: "width=device-width, initial-scale=1"}/
    %title Seva Sahayog Donations 
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = render "layouts/navigation" if user_signed_in?
      - unless flash.blank?
        - flash.each do |key, val|
          .alert.alet-dismissible.fade.in{class: "alert-#{key}"}
            %a.close{'data-dismiss' => 'alert'} X
            %p
              %strong= val   
      = yield

    %footer.footer
      = render "layouts/footer"